services:
  spikesorter:
    image: int-brain-lab/pykilosort:latest
    entrypoint: python /root/Documents/PYTHON/pykilosort/examples/ibl_spikesorting_task.py /mnt/s1/spikesorting/raw_data/mainenlab/Subjects/ZM_2240/2020-01-23/001/raw_ephys_data/probe00/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/s0:/mnt/s0
      - /mnt/s1:/mnt/s1
      - /home/olivier/scratch:/scratch
