services:
  test:
    image: pytorch/pytorch:2.3.0-cuda12.1-cudnn8-runtime
    command: /bin/bash -c "nvidia-smi && python -c 'import torch; print(torch.cuda.is_available())'"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
