services:
  spikesorter:
    image: int-brain-lab/pykilosort:latest
    entrypoint: python /root/Documents/PYTHON/pykilosort/docker/run_pid.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/s0:/mnt/s0
      - /mnt/s1:/mnt/s1
      - /home/$USER/scratch:/scratch
      - /home/$USER/.one:/root/.one
