services:
  spikesorter:
    image: internationalbrainlab/iblsorter:latest
    container_name: spikesorter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/s0:/mnt/s0
      - /home/$USER/.one:/root/.one
      - /mnt/h1:/scratch
