services:
  spikesorter:
    image: int-brain-lab/iblsorter:latest
    entrypoint: python /root/Documents/PYTHON/ibl-sorter/docker/run_pid.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /mnt/s0:/mnt/s0
      - /home/$USER/.one:/root/.one
